drop table if exists direct_message CASCADE;
drop table if exists message CASCADE;
drop table if exists person CASCADE;
drop table if exists pm CASCADE;
create table direct_message (id bigint not null, message varchar(255), receiver_id bigint, sender_id bigint, primary key (id));
create table message (id bigint not null, message varchar(255), primary key (id));
create table person (id bigint not null, age integer not null, name varchar(255), primary key (id));
create table pm (id bigint not null, message_id bigint, person_id bigint, primary key (id));
INSERT INTO person(id,name,age) VALUES (1,'Frank',21);
INSERT INTO person(id,name,age) VALUES (2,'Harris',29);
INSERT INTO person(id,name,age) VALUES (3,'Jane',22);
INSERT INTO message(id,message) VALUES (1,'HEllO WORLD');
INSERT INTO message(id,message) VALUES (2,'HEllO PARIS');
INSERT INTO message(id,message) VALUES (3,'HEllO MOSCOW');
INSERT INTO pm(id,person_id,message_id) VALUES (1,1,1);
INSERT INTO pm(id,person_id,message_id) VALUES (2,2,2);
INSERT INTO pm(id,person_id,message_id) VALUES (3,3,3);
INSERT INTO direct_message(id,message,sender_id,receiver_id) VALUES (4,'Hello Jane',2,3);
INSERT INTO direct_message(id,message,sender_id,receiver_id) VALUES (5,'Hello Harris',3,2);

