DROP TABLE IF EXISTS PERSON CASCADE ;
DROP TABLE IF EXISTS PM CASCADE ;
CREATE TABLE PERSON (id bigint generated by default as identity, name varchar(255),age int, primary key (id));
CREATE TABLE PM (id bigint generated by default as identity, person_id int ,message_id int ) ;
CREATE TABLE MESSAGE (id bigint generated by default as identity, message varchar(255)) ;

INSERT INTO PERSON(id,name,age) VALUES (1,'FRANK',21);
INSERT INTO MESSAGE(id,message) VALUES (1,'HEllO WORLD');
INSERT INTO PM(id,person_id,message_id) VALUES (1,1,1);
