DROP TABLE IF EXISTS PERSON CASCADE ;
DROP TABLE IF EXISTS PM CASCADE ;
CREATE TABLE PERSON (id bigint generated by default as identity, name varchar(255), primary key (id));
CREATE TABLE PM (id bigint generated by default as identity, auth int ,msg int ) ;

INSERT INTO PERSON(id,name) VALUES (1,'FRANK')